# Generated by Django 2.1 on 2018-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=5000)),
                ('author', models.CharField(max_length=100)),
                ('state', models.CharField(choices=['POR VALIDAR', 'VALIDADO', 'RESOLVIDO'], default='POR VALIDAR', max_length=15)),
                ('category', models.CharField(choices=['CONSTRUCTION', 'SPECIAL_EVENT', 'INCIDENT', 'WEATHER_CONDITION', 'ROAD_CONDITION'], max_length=30)),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
    ]
