# Generated by Django 2.1 on 2018-08-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageOccurrences', '0002_occurrence_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='user',
            new_name='author_id',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='author',
        ),
    ]
