# Generated by Django 2.1 on 2018-08-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180809_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
