# Generated by Django 2.1 on 2018-08-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180809_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='author_id',
            new_name='author',
        ),
    ]
